
spring:
  application:
    name: ${SPRING_APPLICATION_NAME:shop-mart}
  profiles:

    active: ${SPRING_PROFILES_INCLUDE:application-shop-mark}

  cloud:
    config:
      label: ${SPRING_CLOUD_CONFIG_LABEL:master}
      username: ${SPRING_CLOUD_CONFIG_USERNAME:pass}
      password: ${SPRING_CLOUD_CONFIG_PASS:pass}
      uri: ${SPRING_CLOUD_CONFIG_URI:http//127.0.0.1:8888}

