# localhost:8888/{profile}/{application}/{label}
# localhost:8888/{application}-{profile}.yml
# localhost:8888/{label}/{application}-{profile}.yml

# localhost:8888/dev/application-shop-mark/master
spring:
  security:
    user:
      name: ${SECURITY_USER:pass}
      password: ${SECURITY_PASS:pass}
      #  url pass:pass@localhost:8888/dev/application-shop-mark/master
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI:file:///Users/Максим/Desktop/server-setting-mart}
          clone-on-start: true
          username: ${GIT_USERNAME:max}
          password: ${GIT_PASSWORD:max}
        bootstrap: true
        default-label: master
      enabled: true

  application:
    name: Config-Server
server:
  port: ${PORT:8888}

encrypt:
  key-store:
    alias: ${ENCRYPT_KEYSTORE_ALIAS:shopmart}
    location: ${ENCRYPT_KEYSTORE_LOCATION:classpath:///server.jks}
    password: ${ENCRYPT_KEYSTORE_PASSWORD:123456}
    secret: changeme